###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'
        networks:
            - app_network

    mariadb:
        container_name: systemdb
        image: 'mariadb:11.0'
        working_dir: /application
        volumes:
            - '.:/application'
            - 'mariadb_data:/var/lib/mysql'  # Volume para persistir os dados do MariaDB
        environment:
            - 'MYSQL_ROOT_PASSWORD=Test2024!@#$%'
            - MYSQL_DATABASE=system
            - MYSQL_USER=system_admin
            - 'MYSQL_PASSWORD=Test2024!@#$%'
        ports:
            - '8003:3306'
        networks:
            - app_network

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        networks:
            - app_network
    
    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        networks:
            - app_network

volumes:
    mariadb_data:  # Definindo o volume para o MariaDB

networks:
    app_network:
        driver: bridge
