name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: 'mariadb:11.0'
        env:
          MYSQL_ROOT_PASSWORD: Test2024!@#$%
          MYSQL_DATABASE: manager
          MYSQL_USER: manager_admin
          MYSQL_PASSWORD: Test2024!@#$%
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
        volumes:
          - mariadb_data:/var/lib/mysql

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, mysqli, exif, gd

    - name: Install dependencies
      run: composer install

    - name: Run tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml

    - name: Lint PHP files
      run: vendor/bin/phpcs --standard=PSR12 src/

volumes:
  mariadb_data:
